references:
  deployment_container: &deployment_container
    docker:
      - image: docker.tw.ee/k8s-deployer:1

jobs:
  publish:
    <<: *deployment_container
    working_directory: ~/aws-kubectl
    resource_class: small
    steps:
      - checkout
      - - persist_to_workspace:
            root: .
            paths:
              - '*'
      - setup_remote_docker
      - attach_workspace:
          at: ~/aws-kubectl
      - run:
          name: Upload docker image
          command: k8s-deployment docker-build docker-push
          environment:
            DEPLOY_DOCKERFILE: ./Dockerfile
            DEPLOY_IMAGE_NAME: gbp-aws-kubectl
            DEPLOY_SLACK_CHANNEL: '#gbp-release'
workflows:
  version: 2
  publish:
    jobs:
      - publish:
          context: kubernetes-production
          filters:
            branches:
              only: master