references:
  deployment_container: &deployment_container
    docker:
      - image: circleci/openjdk:12-jdk

jobs:
  publish:
    <<: *deployment_container
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and deploy docker image
          command: ./gradlew buildDocker publishToSlack --console=plain --no-daemon

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          context: artifactory-deploy
          filters:
            branches:
              only: master